/**
 * Create/rebuild "Message Migration Assessment":
 *   20 questions in 15 minutes, 20 marks — randomly drawn from a 50-question
 *   message-migration engineering pool (Slack/Teams/Viva-style message,
 *   thread/reply, channel/DM, membership, and delta-sync reasoning), one
 *   section, MCQ, 1 mark each.
 *
 * The source material was written as open-ended reasoning questions with a
 * rubric ("expected reasoning") for AI/human grading, not as MCQs. Per
 * explicit instruction (mirroring the Content Migration Assessment), each was
 * converted into a 4-option MCQ: the correct option is the original reasoning,
 * condensed; the 3 distractors are plausible-but-wrong statements written to
 * test the same concept.
 *
 * Idempotent — safe to re-run: questions are only created if missing (matched
 * by title), and the test's section is cleanly rebuilt each run so pool
 * size/timing always match this script, without touching the question bank.
 *
 *   docker exec -w /app neutaraassessment-backend-1 npx tsx prisma/create-message-migration-assessment.ts
 *
 * Env overrides: TEST_TITLE (default "Message Migration Assessment"),
 *                APTITUDE_BANK_NAME (default "Freshers Assessment 1" — used only
 *                to resolve the tenant/admin, not as a question source),
 *                POOL_SIZE (default 20), DURATION_MIN (default 15).
 */
import { PrismaClient, TestStatus } from '@prisma/client'
const prisma = new PrismaClient()

export const MESSAGE_MIGRATION_BANK_NAME = 'Message Migration Questions Bank'

export const MESSAGE_MIGRATION_QUESTIONS: { body: string; options: string[]; correct: number }[] = [
  { body: "Why must a destination channel or DM conversation be created before any messages can be migrated into it?", options: ["Messages are queued centrally and posted regardless of whether a destination container exists", "Messages need a valid destination container to be posted into — you can't post a message to something that doesn't exist yet at the destination", "Channel creation only matters for compliance logging, not for message posting itself", "Messages can be posted first and the containing channel is generated automatically afterward"], correct: 1 },
  { body: "Why does a Direct Message conversation only need identity/workspace-level info at setup, without the same \"channel ID\" concept a channel needs?", options: ["DMs actually do use a channel ID internally, identical to channels, just hidden from the UI", "DM setup is simplified only because DMs are always migrated last, after channels", "A DM is a private one-to-one (or small group) construct without the broader team/channel membership model — there's no equivalent \"channel\" object being created, just the association between participants", "Identity info is required for DMs only to satisfy compliance retention rules, unrelated to structure"], correct: 2 },
  { body: "Why can a failed channel message be automatically retried, but a failed DM cannot?", options: ["DMs are never retried because they are considered lower priority than channel messages", "Conversation order matters for a live back-and-forth exchange; retrying an out-of-order DM risks inserting an older message after newer ones already posted, visibly scrambling the conversation. Channel messages are more tolerant of this", "Channel messages retry automatically only because channels have unlimited storage, unlike DMs", "DM failures can't be retried due to a platform-wide rate limit specific to private messages"], correct: 1 },
  { body: "If a parent message fails to migrate, what should you expect to happen to its thread replies, and why?", options: ["Replies migrate independently and are unaffected by the parent's failure", "Replies are automatically converted into standalone top-level messages instead", "Replies are queued indefinitely until an admin manually deletes the failed parent", "Replies are expected to also fail/not attempt posting, because a reply logically needs its parent to exist at the destination first"], correct: 3 },
  { body: "If a parent message succeeds but one specific reply to it fails, is that necessarily connected to the parent's outcome?", options: ["Yes — a single reply failure always means the parent must be re-migrated", "Yes — reply failures are always caused by the parent losing its destination reference", "No — once the parent has succeeded, each reply's success or failure is independent; a reply failing despite a successful parent points to an issue specific to that reply", "No — but only for channels; replies in DMs always share the parent's outcome"], correct: 2 },
  { body: "Why would message migration for a platform like Slack need a distinct \"reply sync\" step, separate from the initial message fetch?", options: ["Reply sync exists purely to reduce the size of the first fetch request for performance", "Replies are fetched first, then parents are matched to them in a second pass", "Threaded replies may need to be associated back to their parent message via a reference, which may only be fully resolvable after all parent-level messages for a channel have first been fetched", "Reply sync is only needed when migrating between different messaging platforms"], correct: 2 },
  { body: "Why would a migration engine cap the number of retry attempts for something like reply-sync issues instead of retrying indefinitely?", options: ["Retry caps exist only to control cloud API billing costs", "Uncapped retries are technically impossible due to platform rate limits", "Persistent failures (versus transient ones) won't resolve no matter how many times they're retried — capping retries surfaces the item for manual review instead of looping forever", "Reply-sync issues are capped at exactly one attempt by default, unlike other failures"], correct: 2 },
  { body: "Why does closing out a Microsoft Teams \"Team\" require all of its channels to be closed first?", options: ["Teams and channels close independently; there's no dependency between them", "A Team is a container for multiple channels; if channels underneath are still active/open, the container they belong to logically can't be considered finished and closed yet", "Closing a Team automatically force-closes all its channels regardless of their state", "This requirement only applies when the Team has more than a fixed number of channels"], correct: 1 },
  { body: "Why is \"closing and sharing\" (replicating membership at destination) typically scoped to channels only, and not to DMs?", options: ["DMs are excluded only because messaging platforms don't allow migrating DMs at all", "\"Closing and sharing\" applies to DMs too, just under a different internal name", "Channels have a membership/collaboration model similar to what \"closing and sharing\" replicates; DMs are inherently private and small-scale without an equivalent membership structure", "Channels are chosen arbitrarily as a starting point, with DM support planned but unrelated to structure"], correct: 2 },
  { body: "Why would membership/permission replication for a channel need to look up how a source user maps to a destination user, rather than just copying the source identity directly?", options: ["Copying identity directly is disallowed only for legal/compliance reasons, not technical ones", "Identity mapping is only needed when the two platforms use the same authentication provider", "Source and destination platforms are different systems with their own identity spaces — a user's account on the source isn't automatically the same object as on the destination; a mapping step is needed", "Source identities are always reused as-is; mapping exists only for optional custom labeling"], correct: 2 },
  { body: "What happens, logically, if no destination-mapped identity can be found for a source collaborator during permission/sharing replication?", options: ["The system automatically grants access to a generic shared destination account instead", "That collaborator's access can't be replicated as intended — it should surface as a gap/conflict needing resolution, rather than silently skipping or guessing an identity", "The collaborator is silently dropped with no record of the gap", "The entire channel's permission migration is cancelled and rolled back"], correct: 1 },
  { body: "Why would a platform like Viva Engage require files to be uploaded before the message referencing them is posted, when other platforms migrate messages and their attachments closer to together?", options: ["This is a universal requirement across all messaging platforms, not Viva-specific", "Viva requires this only for files larger than a fixed size threshold", "File upload order is arbitrary and has no functional bearing on message posting", "This reflects a platform-specific requirement of how Viva's own posting mechanism works — the message content there may need to reference an already-existing file object, forcing upload-then-post ordering"], correct: 3 },
  { body: "Why would a migration engine include a periodic process whose only job is checking for and resetting \"stuck\" locks, rather than relying on locks always releasing themselves cleanly?", options: ["Locks are only reset manually by an engineer, never by an automated process", "This process exists solely to free up unused database storage, unrelated to locks", "Real systems can fail mid-operation (crash, timeout, network drop) in ways that leave a lock held indefinitely if nothing else intervenes — a periodic safety-net check prevents one failed operation from permanently blocking future message movement", "Stuck locks are impossible in a well-designed system, so this process is purely precautionary and never actually triggers"], correct: 2 },
  { body: "Why would messages only be allowed to move for a thread/workspace when a particular lock is in an \"unlocked\" state, at all?", options: ["The lock exists only to throttle API usage, unrelated to consistency", "Locks are cosmetic and only affect the UI's progress display, not actual processing", "To prevent race conditions — if multiple processes tried to write to the same thread/workspace simultaneously, message order and consistency could be corrupted; the lock ensures only one operation touches that flow at a time", "Unlocking is required only for DMs; channels process without any locking mechanism"], correct: 2 },
  { body: "Why would an engine check for \"delta availability\" via a separate check before actually running a delta message pull, instead of just always attempting a pull?", options: ["Availability checks are required by the destination platform's terms of service", "A delta pull without an availability check would corrupt previously migrated messages", "This check exists only to estimate billing costs before running delta", "Avoids unnecessary work/API calls when there's genuinely nothing new — checking availability first is a lighter-weight operation, useful when delta is manually triggered rather than continuously running"], correct: 3 },
  { body: "Why might delta/incremental syncing for messages be manually triggered from the UI in some cases, rather than always running automatically on its own schedule?", options: ["Manual triggering is required because automatic delta syncing is not technically possible for messages", "Manual triggering exists purely as a legacy UI feature with no operational purpose today", "Automatic delta only runs for channels; DMs always require manual triggering", "Certain workflows (a client requesting a specific point-in-time re-check, or verifying sync as part of a controlled cutover) may call for the engineer/client to decide exactly when a delta check happens, giving more control during sensitive migration phases"], correct: 3 },
  { body: "Why does a workspace-level or ProfileName-level status stay unresolved (not \"completed\") if even one individual conversation/channel underneath is still pending?", options: ["Workspace status is based only on a time elapsed threshold, not component completeness", "Workspace status resolves independently and has no relationship to individual conversations", "This only applies to workspaces with fewer than a fixed number of channels", "Status has to reflect true overall completeness — resolving the top-level status while a component underneath is still incomplete would misrepresent the actual state of the migration"], correct: 3 },
  { body: "Why would a workspace be marked as \"suspended\" specifically when source or destination cloud configuration is missing, rather than just left \"in progress\" indefinitely?", options: ["\"Suspended\" is used only when the client requests a temporary pause", "\"Suspended\" and \"in progress\" are interchangeable labels with no functional difference", "Workspaces are marked \"suspended\" automatically after a fixed number of days regardless of cause", "\"Suspended\" distinguishes a workspace that's blocked on a configuration/setup issue (something an admin needs to fix) from one that's actively working but just slow — an indefinite \"in progress\" label would mask that this needs human action"], correct: 3 },
  { body: "Why might items sitting in a warning/retrying state with a low retry count be reset back to a fresh \"not yet processed\" state during status finalization, rather than left exactly as they are?", options: ["Resetting is done only to reduce the final report's file size", "Items are reset permanently and never attempted again after finalization", "This reset only happens for DMs, never for channel messages", "Gives them another clean attempt through the normal processing path before finally closing out the job, rather than letting a job close with items stuck in an ambiguous in-between state"], correct: 3 },
  { body: "Why would a completed migration report distinguish between \"processed cleanly,\" \"processed with warnings,\" and \"processed with conflicts,\" rather than a single pass/fail outcome?", options: ["The three categories exist only for internal engineering dashboards, never shown to clients", "All three categories require identical follow-up action, so the distinction is purely cosmetic", "\"Processed with warnings\" and \"processed with conflicts\" are the same state under different names", "These represent meaningfully different situations for a client conversation — a clean pass needs no follow-up, a warning may be informational/minor, and a conflict likely needs real remediation; collapsing them would lose information"], correct: 3 },
  { body: "Why would messages be fetched from the source in a separate step before they're posted to the destination, rather than reading from source and posting live in one motion?", options: ["Combining fetch and post is technically impossible across different messaging platforms", "Separating them exists purely to satisfy a compliance audit trail requirement", "Fetching and posting are combined by default; separation only happens for large channels", "Separating fetch and post lets each step be retried/monitored independently — a posting failure doesn't require re-fetching from source again, and a fetch issue doesn't imply anything about the destination posting logic"], correct: 3 },
  { body: "A client using an \"export/JSON dump\" based migration approach (rather than live API access) asks why this method exists at all if API-based migration is available. Why might a client need this alternate path?", options: ["Export-based migration is always faster than API-based migration, regardless of platform", "This approach exists only for clients migrating fewer than a fixed number of messages", "JSON-dump migration is required whenever the destination platform is Microsoft Teams", "Some platforms/tenants may not expose full API access (compliance-locked environments, limited API surface, or client IT policy restricting live connections) — an export-based ingestion path lets migration proceed from a client-provided data dump instead"], correct: 3 },
  { body: "Why would channel messages and their replies both funnel through similar underlying processing logic, despite being conceptually different (a message vs. a reply to a message)?", options: ["They use identical logic because replies are technically indistinguishable from standalone messages", "Shared logic exists only to reduce the codebase's line count, with no functional benefit", "Replies actually use a completely separate, unrelated processing pipeline from messages", "Both are fundamentally \"content to post to a destination location,\" differing mainly in their dependency (replies need their parent) — reusing similar logic with an added parent-check is more consistent than building a separate mechanism"], correct: 3 },
  { body: "Why does discovering what channels and DMs exist at the source need to happen as its own step before message fetching even begins?", options: ["Discovery and message fetching always happen simultaneously in the same API call", "This step exists only to generate the client's cost estimate, not to scope actual work", "Message fetching can begin before discovery finishes, as long as it retries later", "You need the full list of containers (channels/DMs) that exist before you know what to fetch messages from — message-level work depends on the container-level discovery having already identified the scope"], correct: 3 },
  { body: "Why might migrating a very active, high-volume channel take proportionally longer per message than a quiet channel, even with the same total message count comparison?", options: ["High-volume channels are always throttled deliberately regardless of threading", "Per-message time is identical regardless of channel activity; only total time differs", "Active channels take longer only because they contain more attachments, never due to threading", "High message-density channels are more likely to have extensive threading/replies, which adds parent-dependency-checking overhead per message that a quiet channel with mostly standalone messages wouldn't have as much of"], correct: 3 },
  { body: "Why would a client ask \"will my message timestamps be preserved,\" and what would you need to understand about the workflow to answer confidently?", options: ["Timestamps are never preserved on any platform, so the answer is always \"no\"", "Timestamps are always preserved exactly, so the question doesn't require platform-specific knowledge", "Timestamp preservation depends only on message length, not platform behavior", "Whether the original send time is preserved as metadata during posting to the destination (vs. showing the migration's actual posting time) is a real behavioral question — an engineer should know the platform's actual handling rather than assuming"], correct: 3 },
  { body: "Why is a periodic \"safety net\" scheduler (like the lock-reset process) a reasonable design choice in a distributed, retry-heavy system generally, beyond just this specific lock scenario?", options: ["Safety-net schedulers are only useful in single-server systems, not distributed ones", "This pattern is specific to messaging migration and not used in other distributed systems", "A safety-net scheduler replaces the need for retry logic entirely", "Distributed systems with many moving parts and retries inevitably have edge cases where something doesn't clean up after itself perfectly — a periodic reconciliation/safety-net process is a common defensive pattern to catch and correct drift"], correct: 3 },
  { body: "A client says their Slack channel has been \"in progress\" for days with barely any messages showing as processed, but there's no conflict shown anywhere. First check?", options: ["Immediately assume the channel is corrupted and needs to be re-created from scratch", "Check only the client's browser cache, since that's the most common cause", "Escalate to engineering immediately without checking threading or progress trend", "Check whether this is a heavily-threaded channel where reply-sync dependency logic is adding processing overhead, vs. a genuinely stalled process — look at whether counts are moving at all, even slowly, before escalating"], correct: 3 },
  { body: "A client asks why some of their DMs never came over, while all their channel messages migrated successfully. What's your triage path?", options: ["Assume DMs are disabled entirely for this client's plan tier", "Assume the destination platform doesn't support DMs at all", "Check only whether the DMs were sent outside business hours", "Check whether the failed DMs hit a genuine conflict — DMs don't auto-retry, so any DM-level failure stays failed until manually addressed, unlike a channel message that might self-heal"], correct: 3 },
  { body: "A Microsoft Teams \"Team\" won't close out even though the client says \"all our conversations are done.\" What do you check?", options: ["Check only the Team's overall message count against the client's estimate", "Assume the Team object itself is corrupted and needs to be recreated", "Check whether the client has admin rights on the destination Team", "Check the status of each individual channel under that Team — if even one channel hasn't completed its own close-out, the Team-level closure will be blocked regardless of message-level completion"], correct: 3 },
  { body: "A client's replies/threads show as \"conflict\" but the original parent messages show as processed successfully. What's the likely cause, and what do you check?", options: ["Assume the parent must be re-migrated to fix the replies", "Assume this always indicates a corrupted thread requiring a full channel restart", "Assume the replies were duplicated and check for duplicate parent records instead", "Since the parent succeeded, the reply failure is likely independent (not a cascading parent-dependency issue) — investigate the specific reply's own error rather than assuming it's tied to the parent's outcome"], correct: 3 },
  { body: "A client insists their delta sync should have picked up new messages sent yesterday, but nothing shows as new. First check?", options: ["Assume the messages were sent to the wrong channel entirely", "Assume delta sync is broken and switch immediately to a full one-time re-migration", "Check only whether the client's account has correct destination licensing", "Confirm whether delta was actually re-triggered/checked since those messages were sent (especially if delta availability checking is manually initiated rather than continuous) — \"not run yet\" is a very different problem than \"ran and found nothing\""], correct: 3 },
  { body: "Messages in a channel appear to be posting in the wrong order compared to when they were originally sent. What do you investigate?", options: ["Assume this is always a display-only issue with no real reordering", "Assume this only happens when migrating from Teams to Slack specifically", "Assume the client's local timezone setting is the sole cause in every case", "Consider whether this is a DM (where strict ordering is critical and no-retry is enforced specifically to protect this) versus a channel — if a channel, check whether retries occurred and possibly reordered something; if a DM shows this, it's more serious"], correct: 3 },
  { body: "A client on Viva Engage reports message counts appear stalled while file upload counts are actively increasing. Is this a problem?", options: ["Yes — file and message counts should always increase in lockstep on every platform", "Yes — this always indicates the message queue has silently failed", "No — but only because Viva doesn't actually track message counts accurately", "Not necessarily — Viva's workflow requires files to upload before their associated messages post, so file progress moving while message progress lags briefly is consistent with expected sequencing"], correct: 3 },
  { body: "A client's workspace status shows \"suspended.\" What's your first question to the client or first internal check?", options: ["Check only whether the client's payment method has expired", "Assume the workspace was manually paused by another engineer and wait for them to resume it", "Assume suspension means the migration failed permanently and must restart from zero", "Check whether source or destination cloud configuration is actually present/valid for that workspace — suspended specifically flags a config/setup gap needing to be fixed, distinct from a normal in-progress delay"], correct: 3 },
  { body: "A client asks why their final report shows \"processed with some conflicts\" rather than a clean \"processed,\" even though the vast majority of messages look fine to them in a quick check.", options: ["Tell them the label is a system default and doesn't reflect real conflicts", "Tell them \"with conflicts\" and \"processed cleanly\" mean the same thing operationally", "Tell them to ignore the report entirely since visual spot-checks are more reliable", "Explain that the summary status reflects the true state including a smaller number of unresolved conflict items — worth walking the client through what specifically remains in conflict rather than letting the label alone cause alarm"], correct: 3 },
  { body: "A client's shared channel membership at destination doesn't match who had access at the source. What's the likely root cause to check first?", options: ["Assume the destination platform has a hard cap on channel membership size", "Assume membership was randomly dropped due to a network timeout", "Assume the client's source platform doesn't track membership accurately", "Check whether all source collaborators had a successful identity mapping to a destination account — anyone without a resolvable destination identity would be a known gap in the membership replication, not a random omission"], correct: 3 },
  { body: "A client using the JSON-export-based ingestion path reports messages appear \"frozen\" partway through. What's different about troubleshooting this vs. an API-based migration stall?", options: ["Troubleshooting is identical to API-based migration; check API rate limits first", "Assume the export file is irrelevant and check only destination-side connectivity", "Assume JSON-based migrations can never stall, so this must be a reporting display bug", "This path depends on the client-provided export file itself rather than live API connectivity — check whether the export file is complete/valid and correctly matches expectations, since issues here trace back to the source data dump"], correct: 3 },
  { body: "A client reports their message migration \"completed,\" but they're still seeing membership/sharing updates happening afterward. Is this expected?", options: ["No — this always indicates the completion report was generated in error", "No — membership updates should only ever happen before messages, never after", "Yes, but only for clients using the JSON-export ingestion path", "Yes — closing and membership/sharing replication is a distinct step that follows message migration completion, so activity continuing there after messages finish is normal sequencing"], correct: 3 },
  { body: "Conceptually, how would you expect the system to track whether a given reply is allowed to post yet, given its dependency on its parent?", options: ["It only checks the reply's own timestamp against a fixed delay window, unrelated to the parent", "It relies on the destination platform to reject out-of-order replies automatically", "It doesn't track this at all; replies and parents post fully independently of each other", "It likely stores/checks a reference from reply to parent (some form of parent identifier) and checks the parent's own status before allowing the reply's posting logic to proceed"], correct: 3 },
  { body: "Why would a lock-based mechanism make sense for controlling message posting into a given thread/workspace, at a conceptual level?", options: ["Locks exist only to prevent duplicate billing charges for the same message", "Locks are used only for DMs; channels don't need concurrency protection", "Locks primarily exist to control UI refresh rate, not actual data consistency", "It prevents concurrent processes from writing to the same conversation simultaneously, which could otherwise interleave/corrupt message ordering — a lock enforces one-at-a-time access to that resource"], correct: 3 },
  { body: "How might the system distinguish, internally, between a DM-type conversation and a channel-type conversation, such that different retry rules can apply to each?", options: ["It infers type dynamically each time by counting the number of participants at retry time", "It uses a separate, entirely unrelated database for each conversation type", "Retry rules are identical for both; the perceived difference is coincidental", "It likely tags/categorizes conversation records by type at creation, and applies retry logic conditionally based on that type flag rather than treating all conversations identically"], correct: 3 },
  { body: "Conceptually, how would a periodic safety-net process (like a lock-reset check) know a lock is actually stuck versus legitimately still in active use?", options: ["It contacts the process holding the lock directly to ask if it's still active", "It assumes every lock older than one second is stuck, regardless of operation type", "It relies on the client to manually report locks that seem stuck", "It likely uses a time-based threshold (locked for longer than any normal operation should reasonably take) as the signal to treat it as stuck rather than actively held, rather than trying to definitively prove the holding process is dead"], correct: 3 },
  { body: "Why would identity mapping (source user to destination user) for permission/membership replication logically need to be resolved and cached rather than looked up fresh every single time it's needed?", options: ["Caching is required only because live lookups are technically disabled by most platforms", "Fresh lookups would be faster, so caching is purely a legacy inefficiency", "Caching exists only to reduce the client-facing report's file size", "The same user likely appears across many channels/items — resolving and reusing a cached mapping avoids redundant lookups and keeps behavior consistent for that user across the whole migration"], correct: 3 },
  { body: "How would you expect a system to structure the difference between \"picking/discovery\" and \"actual migration\" as two logically separate phases for messages, similar to content?", options: ["The two phases are actually merged for messages, unlike content, due to platform constraints", "Discovery only applies to content migration; messages skip straight to posting", "Separating them exists solely to produce two separate client invoices", "Discovery/fetch determines what exists and needs to move; the migration/posting phase actually writes it to the destination — separating them allows independent retry/monitoring and mirrors the same discovery-then-transfer pattern seen in content migration"], correct: 3 },
  { body: "Why might a migration engine need to decide how to handle a message that was edited at the source after it was already migrated?", options: ["Edited messages are always excluded from migration entirely, regardless of timing", "Edits are automatically applied to the destination copy instantly with no dependency on delta/detection", "Edited messages must always be migrated as brand new messages, never associated with the original", "An edited-after-migration message represents a genuine post-migration change; the system needs a defined behavior (e.g., captured by a later delta pass) rather than silently ignoring it, since the destination copy would otherwise reflect stale content"], correct: 3 },
  { body: "Why would @mentions of users need to be translated/remapped when migrating a message rather than copied as-is?", options: ["Mentions are purely cosmetic text and never contain an actual identity reference", "Mentions are always stripped out entirely during migration since they can't be preserved", "Mention remapping is optional and only affects message formatting, not functionality", "A mention typically embeds a reference to a specific user's identity on the source platform; without remapping to the corresponding destination identity, the mention would point to a non-existent or wrong user at destination"], correct: 3 },
  { body: "Why might a migration engine need to throttle its own posting rate to the destination platform, even if the source data is ready to send immediately?", options: ["Throttling exists only to intentionally slow down migrations for larger clients", "Rate limits only apply to file uploads, never to message posting itself", "The source platform's speed is always the only relevant constraint on posting rate", "Destination platforms typically enforce their own API rate limits; posting faster than those limits allow would trigger throttling/errors, so the engine needs to pace itself according to the destination's constraints"], correct: 3 },
  { body: "If a message was deleted at the source after being discovered but before it was migrated, what's the reasonable expected behavior?", options: ["The message should be migrated anyway since it was already discovered and queued", "The entire channel's migration should be cancelled whenever any single message is deleted mid-process", "Deleted messages are always converted into a placeholder message noting the deletion", "The engine should detect the deletion (or the absence of the message when it goes to fetch/post it) and skip migrating it rather than posting content that no longer exists at the source of truth"], correct: 3 },
  { body: "Why would emoji reactions on a message need to be handled as part of, or after, the message's own successful migration, rather than independently beforehand?", options: ["Reactions are migrated completely independently and have no dependency on the message itself", "Reactions are always migrated before the message to pre-allocate space for them", "Reactions are never migrated under any circumstances, regardless of platform", "A reaction is attached to a specific message — the message must exist at the destination first before a reaction referencing it can be attached there, mirroring the same target-must-exist-first dependency seen elsewhere in migration"], correct: 3 },
]

async function main() {
  const testTitle = process.env.TEST_TITLE || 'Message Migration Assessment'
  const aptitudeBankName = process.env.APTITUDE_BANK_NAME || 'Freshers Assessment 1'
  const poolSize = Number(process.env.POOL_SIZE) || 20
  const durationMin = Number(process.env.DURATION_MIN) || 15

  // Only used to resolve the tenant/admin — this test's questions are entirely its own pool.
  const aptiBank = await prisma.questionBank.findFirst({ where: { name: aptitudeBankName } })
  if (!aptiBank) throw new Error(`Bank "${aptitudeBankName}" not found — needed to resolve tenant/admin.`)
  const tenantId = aptiBank.tenantId

  const admin = await prisma.user.findFirst({
    where: { tenantId, role: { in: ['SUPER_ADMIN', 'COMPANY_ADMIN'] } },
    orderBy: { createdAt: 'asc' },
  })
  if (!admin) throw new Error('No admin user found for the tenant.')

  let bank = await prisma.questionBank.findFirst({ where: { name: MESSAGE_MIGRATION_BANK_NAME, tenantId } })
  if (!bank) {
    bank = await prisma.questionBank.create({ data: { name: MESSAGE_MIGRATION_BANK_NAME, tenantId, description: 'Message migration engineering reasoning MCQ pool — message/thread/reply, channel/DM, membership, delta-sync reasoning.' } })
  }

  let created = 0
  for (let i = 0; i < MESSAGE_MIGRATION_QUESTIONS.length; i++) {
    const title = `Message Migration Q${i + 1}`
    const existing = await prisma.question.findFirst({ where: { bankId: bank.id, title } })
    if (existing) continue
    const q = MESSAGE_MIGRATION_QUESTIONS[i]
    await prisma.question.create({
      data: {
        bankId: bank.id, type: 'MCQ_SINGLE', title, body: q.body,
        difficulty: 'MEDIUM', points: 1, domain: 'Message Migration Engineering',
        options: { create: q.options.map((text, idx) => ({ text, isCorrect: idx === q.correct, order: idx })) },
      },
    })
    created++
  }
  console.log(`Message Migration bank: ${created} question(s) created, ${MESSAGE_MIGRATION_QUESTIONS.length - created} already existed.`)

  const questions = await prisma.question.findMany({
    where: { bankId: bank.id, title: { startsWith: 'Message Migration Q' } },
    orderBy: { createdAt: 'asc' },
    select: { id: true },
  })
  if (questions.length < poolSize) throw new Error(`Only ${questions.length} message migration questions — need at least ${poolSize}.`)

  const instructions = `Message Migration Assessment — ${durationMin} minutes, a random ${poolSize} of ${questions.length} questions, 1 mark each. Choose the best option.`

  let test = await prisma.test.findFirst({ where: { title: testTitle, tenantId } })
  if (!test) {
    test = await prisma.test.create({
      data: {
        title: testTitle, domain: 'Message Migration Engineering', duration: durationMin,
        status: TestStatus.DRAFT, proctoring: true, enforceViolations: false, sebRequired: false,
        tenantId, createdById: admin.id, instructions,
      },
    })
    console.log(`created test "${testTitle}"`)
  } else {
    const secs = await prisma.testSection.findMany({ where: { testId: test.id } })
    for (const s of secs) await prisma.testQuestion.deleteMany({ where: { sectionId: s.id } })
    await prisma.testSection.deleteMany({ where: { testId: test.id } })
    await prisma.test.update({ where: { id: test.id }, data: { duration: durationMin, instructions } })
    console.log(`rebuilt existing test "${testTitle}"`)
  }

  const section = await prisma.testSection.create({
    data: { testId: test.id, title: 'Message Migration Engineering', skill: 'GENERAL', order: 0, timeLimit: durationMin * 60, pickCount: poolSize,
      description: `${poolSize} questions (randomly drawn from a bank of ${questions.length}) covering message migration workflow, troubleshooting, and architecture reasoning. 1 mark each.` },
  })
  await prisma.testQuestion.createMany({
    data: questions.map((q, i) => ({ testId: test!.id, sectionId: section.id, questionId: q.id, order: i, points: 1 })),
  })

  console.log(`\n✅ "${testTitle}": ${poolSize}/${questions.length} questions, ${durationMin} min, ${poolSize} marks. Status DRAFT — publish it in the admin UI to use.`)
}

if (require.main === module) {
  main().catch(e => { console.error('❌ create-message-migration-assessment failed:', e); process.exit(1) }).finally(() => prisma.$disconnect())
}
