/**
 * Create/rebuild "Content Migration Assessment":
 *   20 questions in 15 minutes, 20 marks — randomly drawn from a 50-question
 *   content-migration engineering pool (workflow/sequence/dependency reasoning,
 *   troubleshooting triage, architecture/implementation reasoning), one
 *   section, MCQ, 1 mark each.
 *
 * The source material was written as open-ended reasoning questions with a
 * rubric ("what a strong answer demonstrates") for AI/human grading, not as
 * MCQs. Per explicit instruction, each was converted into a 4-option MCQ: the
 * correct option is the original reasoning, condensed; the 3 distractors are
 * plausible-but-wrong statements written to test the same concept.
 *
 * Idempotent — safe to re-run: questions are only created if missing (matched
 * by title), and the test's section is cleanly rebuilt each run so pool
 * size/timing always match this script, without touching the question bank.
 *
 *   docker exec -w /app neutaraassessment-backend-1 npx tsx prisma/create-content-migration-assessment.ts
 *
 * Env overrides: TEST_TITLE (default "Content Migration Assessment"),
 *                APTITUDE_BANK_NAME (default "Freshers Assessment 1" — used only
 *                to resolve the tenant/admin, not as a question source),
 *                POOL_SIZE (default 20), DURATION_MIN (default 15).
 */
import { PrismaClient, TestStatus } from '@prisma/client'
const prisma = new PrismaClient()

export const CONTENT_MIGRATION_BANK_NAME = 'Content Migration Questions Bank'

export const CONTENT_MIGRATION_QUESTIONS: { body: string; options: string[]; correct: number }[] = [
  { body: "Why must a folder exist at the destination before the files inside it can be migrated?", options: ["Folders are the containers that provide a valid destination target for the files to land in", "Files can only be migrated in alphabetical order after their parent folder is indexed", "Destination folders require manual approval before any file can enter them", "Files are migrated first and folders are generated afterward to contain them"], correct: 0 },
  { body: "Why does content discovery (finding what needs to move) happen as a distinct step before the actual move, rather than moving each item the moment it's found?", options: ["Moving items immediately would violate cloud provider terms of service", "Discovery and transfer are different types of work with different failure/speed characteristics; separating them lets scope be fully mapped before committing to moves, and lets transfer run in parallel across items", "Discovery must finish first because transfer work requires a fixed total byte count to allocate storage", "Items found later in discovery are considered lower priority and are skipped"], correct: 1 },
  { body: "A client's small files finish migrating well before their large files, even though everything started simultaneously. Is this expected?", options: ["No — all files should complete in the same amount of time regardless of size", "No — this indicates the small files were migrated using a different destination account", "Yes — large files typically use a chunked/multi-part transfer suited to their size, which is inherently slower per file than a single-request transfer for small files", "Yes, but only because large files are queued after all small files complete"], correct: 2 },
  { body: "Why would permissions/collaborator access only begin migrating after the bulk content transfer is substantially underway, rather than at the very start?", options: ["Permission systems require a warm-up period before accepting any API calls", "Permissions are migrated first for admin accounts and last for standard users", "Permissions apply to specific files/folders — the destination object must exist before access can be granted to it", "Access migration is throttled deliberately to reduce API costs, unrelated to content transfer"], correct: 2 },
  { body: "Why does permission migration compare source and destination permissions rather than just copying the full source permission list over?", options: ["Comparing is required by data protection law before any permission can be copied", "Some permissions may already exist at destination (inherited or added independently); comparing avoids duplicating or conflicting entries and migrates only the genuinely missing ones", "The source permission list is usually incomplete, so comparison fills in gaps from a template", "Copying the full list is not technically possible across different cloud platforms"], correct: 1 },
  { body: "Why would a hyperlink inside a migrated document still point to the old (source) location instead of the new one, and is that necessarily a bug?", options: ["Yes, it's always a bug and indicates the migration engine has crashed", "Link rewriting depends on the link's target having already migrated; if the target hasn't finished, the link legitimately can't be rewritten yet — it should resolve once the target completes", "Hyperlinks are permanently excluded from migration and must be updated manually", "The link only updates once the client manually requests a \"fix links\" action"], correct: 1 },
  { body: "Why is there a separate \"pre-scan\" concept that runs before migration even begins, if migration already has its own discovery step?", options: ["Pre-scan exists only to generate the client's invoice before work starts", "Pre-scan and discovery are the same process run twice for redundancy", "Pre-scan builds a full manifest/audit of the source up front for scoping, estimating volume/duration, and catching structural issues — distinct from the live discovery that happens once migration is running", "Pre-scan is only required for delta migrations, never for one-time migrations"], correct: 2 },
  { body: "What's the functional difference between a \"one-time\" and a \"delta\" migration?", options: ["One-time only migrates folders; delta only migrates files", "One-time is a full copy as of a point in time; delta captures only what's changed since then, keeping ongoing activity in sync without re-copying everything", "Delta is simply a faster version of one-time with no functional difference otherwise", "One-time requires source access removal immediately after; delta does not"], correct: 1 },
  { body: "Why might a delta scan report \"no changes found\" for a folder, but that's not necessarily the final answer for that branch of the folder tree?", options: ["\"No changes found\" always means the entire branch is fully confirmed clean", "The scan only checks files modified in the last 24 hours, regardless of folder depth", "Child folders are scanned on a separate weekly schedule unrelated to the parent result", "The system may still need to check child folders recursively — absence of change at one level doesn't guarantee absence deeper in the tree"], correct: 3 },
  { body: "Why does delta/incremental change detection sometimes behave differently depending on which cloud platform is the source?", options: ["Some platforms don't support delta migration at all and must be re-migrated fully each time", "Not all cloud providers track/expose changes the same way — some support stable ID-based tracking, others primarily path-based — so detection has to match what the source platform offers", "The difference only exists due to differing API rate limits, not change-tracking mechanisms", "All major cloud platforms expose identical change-tracking APIs, so no difference should occur"], correct: 1 },
  { body: "A file fails and lands in a conflict state. On the next check, it's succeeded without anyone touching it. What most likely happened?", options: ["The client's IT team manually resolved it without notifying support", "Automatic retry — many failures (e.g., transient network issues, temporary rate limiting) are retried on a delay and resolve once the transient condition clears", "The file was silently skipped and a placeholder was inserted instead", "The system reclassified the failure as a warning rather than a conflict"], correct: 1 },
  { body: "Two files hit conflicts for different reasons. One resolves automatically after some time; the other doesn't, no matter how long you wait. Why the difference?", options: ["File size determines whether retries are attempted at all", "Only files uploaded on weekdays are eligible for automatic retry", "Automatic retry helps transient failures; a persistent blocker (genuine naming collision, missing permission, unsupported type) won't resolve just by waiting since retry doesn't change the underlying condition", "The retry system randomly selects which conflicts to resolve automatically"], correct: 2 },
  { body: "Why does automatic retry logic typically use increasing delays between attempts rather than retrying immediately and repeatedly?", options: ["Increasing delays are required to comply with cloud storage licensing agreements", "Delays are randomized, not increasing, to avoid predictable retry patterns", "The delay increases only to reduce the client's dashboard refresh load", "Immediate rapid retries can worsen the exact problem causing the failure (e.g., hitting a rate limit harder) and waste resources; increasing delays give transient conditions time to clear"], correct: 3 },
  { body: "Why would folder-level automatic retry include a duplicate-check step that file-level retry doesn't need in the same way?", options: ["A folder retry might be attempting to recreate something that partially succeeded before failing; checking for an existing destination folder avoids duplicate/orphaned structures — files are a more atomic unit, less prone to this ambiguity", "Folders are retried less often than files, so the check is a safeguard against rare edge cases", "Duplicate-checking is a legal requirement specific to folder structures, not files", "File-level retries already delete and recreate the file, making a duplicate check redundant"], correct: 0 },
  { body: "Why does the system track a \"still working, just slow\" state separately from an actual failure state, instead of treating anything that takes too long as failed?", options: ["Slow migrations are automatically capped and forced into a failure state after a fixed time", "This state exists only to pause billing during long-running migrations", "There is no such distinction — all delays are eventually reported as failures", "Some legitimate migrations (very large content sets) can validly take longer than a typical threshold without anything being wrong; a distinct state preserves the difference between \"still working\" and \"actually stuck/broken\""], correct: 3 },
  { body: "A migration pair takes an unusually long time just to start moving content, even though the client says everything looks configured correctly. What's a plausible explanation that isn't \"something is broken\"?", options: ["The client's account was likely suspended without their team's knowledge", "Very large source content sets can simply take a long time to fully scan/discover before the bulk of transfer work becomes visible in progress metrics — a long discovery phase isn't the same as being stuck", "The destination platform is incompatible and must be swapped before continuing", "This always indicates a corrupted migration job requiring a full restart"], correct: 1 },
  { body: "Why would migrating collaboration/sharing settings for a piece of content require checking both the source and the destination, rather than just reading what exists at the source?", options: ["Destination-only checks are sufficient; source is checked purely for audit logging", "Checking both is required only when migrating between different cloud vendors", "This dual-check exists solely to generate the client-facing permissions report", "The goal is to identify what's missing at the destination — checking only the source risks re-adding permissions already present in some form, creating duplication or unintended conflicts"], correct: 3 },
  { body: "Why does a hyperlink-fixing step need to happen after the file containing the link has already been migrated, rather than while the file itself is still being transferred?", options: ["Hyperlink-fixing and file transfer always run in the exact same process step", "The link content lives inside the file — you need the migrated copy of the file to exist at the destination before you can open it and rewrite what's inside it", "Links are fixed before transfer to avoid double-processing the file later", "This ordering is only true for large files, not small ones"], correct: 1 },
  { body: "If a client wants to know whether their migration overall is \"done,\" why isn't file/folder transfer completion alone a sufficient answer?", options: ["Transfer completion is sufficient; permissions and hyperlinks are optional add-ons", "\"Done\" also requires the client to manually confirm each file individually", "Full completion also depends on downstream steps (permissions, hyperlinks) which run after and depend on content transfer — reporting \"done\" based on transfer alone would be premature", "Transfer completion already includes permissions and hyperlinks by definition"], correct: 2 },
  { body: "Why would a client's report show some files \"processed\" and others still \"in queue\" for a very long time, even with no conflicts showing anywhere?", options: ["Files \"in queue\" for a long time are always secretly failing without being reported", "Queued files are lower-priority items the client marked to migrate last", "Only one file can be processed at a time across the entire migration", "Migration is generally processed in parallel batches subject to capacity/throughput limits — a large backlog can simply mean many items are legitimately still waiting their turn"], correct: 3 },
  { body: "Why might migrating from a platform like Dropbox behave differently, operationally, than migrating from a platform that tracks changes by stable internal IDs?", options: ["Dropbox doesn't support any form of change tracking, so it always requires full re-migration", "ID-based platforms are always faster regardless of change tracking mechanism", "Path-based platforms track items by location/name rather than a persistent ID, so a rename or move can look like a different item entirely — versus ID-based platforms where identity survives a rename/move", "This difference only affects file permissions, not file identity or change detection"], correct: 2 },
  { body: "Why is scanning for embedded/shared links treated as a distinct step from the general file-move step, rather than doing everything in one pass while the file transfers?", options: ["Link scanning must occur before transfer to determine file transfer order", "Combining them would violate most cloud providers' API terms of service", "Link scanning is only performed if the client explicitly pays for an add-on", "Detecting links usually means reading/parsing file content, different work than copying bytes — separating them lets each be optimized and retried independently without redoing the other if just one fails"], correct: 3 },
  { body: "Why would a client migrating from one cloud to another still need active internet/API access to the source platform well into the project, rather than just an initial export?", options: ["Source access is required only to generate the final invoice", "Ongoing delta/incremental syncing (to catch changes made after the initial migration) requires continued access to check for and pull new changes from the source", "Access is needed solely for the destination platform to verify licensing", "This is only true if the client's migration includes video files"], correct: 1 },
  { body: "Why does a folder that fails to migrate block its children from being attempted, in a well-designed content migration system?", options: ["Blocking children is a manual safeguard the support team applies case by case", "Children are only blocked if the folder contains more than a fixed number of files", "This only happens when migrating between the same cloud vendor's two accounts", "Children need their parent folder to exist at the destination as their target location — if the parent hasn't successfully landed, there's nowhere valid to put the children yet"], correct: 3 },
  { body: "A client asks: \"Can you just skip the failed folder and migrate everything inside it directly to the top level?\" What's the right way to think through this request?", options: ["This is always the correct fix and should be applied automatically for any failed folder", "This changes the destination structure (flattening what was meant to stay nested) and may not preserve intended organization/permissions context — worth clarifying whether the client wants a structural change or just an unstick workaround", "This request is technically impossible and must be refused outright", "This only affects folders larger than a certain file count threshold"], correct: 1 },
  { body: "Why does exponential backoff (increasing delay per retry attempt) eventually stop retrying rather than continuing indefinitely?", options: ["Retries stop only when the client's storage quota is exceeded", "Backoff continues indefinitely by design; capping is a bug, not a feature", "Indefinite retry on a persistent (non-transient) failure wastes resources and never resolves the underlying issue — capping retries surfaces genuinely broken items for manual review", "Retries stop after exactly one attempt regardless of backoff strategy"], correct: 2 },
  { body: "Why would migrating a very large single file sometimes be more failure-prone than migrating many small files of the same total size?", options: ["Large files are always corrupted during compression before transfer", "Small files are exempt from network interruption due to their size", "Failure-proneness is unrelated to file size and depends only on file type", "A large file transferred as one continuous unit (or fewer, larger chunks) has more exposure time to network interruption/timeout per attempt; many small files fail and retry independently and quickly"], correct: 3 },
  { body: "Why is a post-migration report generated only after permissions and hyperlinks have also finished, not right after the bulk content transfer completes?", options: ["Report generation is delayed purely to allow time for manual proofreading", "The report only reflects content transfer; permissions/hyperlinks are separate reports", "Reports are generated on a fixed weekly schedule unrelated to job completion", "A report generated too early would be inaccurate — it needs to reflect the true final state including the steps that run after content transfer, or it risks telling the client \"done\" prematurely"], correct: 3 },
  { body: "A client says \"my migration has been running for 10 hours and looks stuck at the same percentage.\" What do you check first?", options: ["Immediately restart the entire migration job from scratch", "Check only the client's internet speed, since that's always the cause", "Whether the count is genuinely frozen over a meaningful window vs. moving slowly through a large or large-file-heavy backlog — only treat as stuck if truly flat over time", "Assume it's failed and generate a report for the client immediately"], correct: 2 },
  { body: "A folder shows \"processed\" but none of the files that were supposed to be inside it appear at the destination. What's your first hypothesis?", options: ["The destination account storage limit was silently reached", "Folder-level and file-level success are somewhat independent — check the actual status of the individual files rather than assuming folder status implies file status", "The folder was processed on a different destination account by mistake", "This always means the folder was deleted at the source mid-migration"], correct: 1 },
  { body: "A client reports a hyperlink still points to the old location weeks after \"migration complete\" was reported. What do you check?", options: ["Whether the client's browser cache needs to be cleared", "Whether the link was manually edited by the client after migration", "Whether the link's target actually completed migration successfully — if the target is still pending or failed, the link can't have been rewritten correctly", "Whether the link uses HTTP instead of HTTPS"], correct: 2 },
  { body: "Permissions for a specific file didn't carry over, but the file itself migrated fine. What's your first check?", options: ["Whether the file's name contains special characters", "Whether the collaborator/permission actually existed distinctly at the source (vs. being inherited from a parent that may lack the same permission) — and whether a matching identity exists at destination to grant it to", "Whether the file was migrated using the delta process instead of one-time", "Whether the client's destination account has enough storage remaining"], correct: 1 },
  { body: "A client asks why some of their files show as \"conflict\" while 95% of similarly-sized files migrated fine. What's your triage approach?", options: ["Assume a systemic outage and escalate to engineering immediately", "Re-run the entire migration job to see if the same files fail again", "Check whether the client's timezone setting is causing a mismatch", "Look at the specific error/reason attached to the conflicting files rather than assuming it's a general system issue — since the vast majority succeeded, the cause is likely item-specific"], correct: 3 },
  { body: "A large migration job appears to have completely stopped progressing, with zero movement for several hours, unlike a normal slow-but-moving job. What's your escalation path?", options: ["Reassure the client it's normal for large jobs and take no further action", "Distinguish \"slow\" from \"stalled\" first — if genuinely flat with no progress at all, this is a legitimate stuck condition worth escalating", "Immediately cancel and restart from a fresh migration pair", "Assume the report is a display bug and ignore the percentage entirely"], correct: 1 },
  { body: "A client's delta sync shows \"no changes found\" but the client insists they've been actively adding files. What do you check?", options: ["Assume the client is mistaken and no further check is needed", "Confirm delta is actually configured/running for the correct account/path, and consider that a \"no changes at this level\" result may still be checking deeper folder branches", "Check only whether the client's files are larger than the delta size limit", "Restart the one-time migration instead of investigating delta"], correct: 1 },
  { body: "A client on Dropbox reports that files they renamed at the source aren't reflecting the rename at the destination during delta sync. What's the likely mechanism, and what do you check?", options: ["Check whether the client's Dropbox plan supports renaming at all", "Check whether the destination platform blocks renamed files by policy", "Path-based source platforms can effectively treat a rename as \"old path gone, new path appeared\" rather than an in-place update — check whether the rename is being interpreted as a move/new item", "Assume the rename simply hasn't synced yet and wait 24 hours with no other check"], correct: 2 },
  { body: "A client insists their migration \"finished\" based on the content transfer percentage hitting 100%, but is asking why they still see activity in the report. What do you tell them?", options: ["Tell them the report is malfunctioning and should be ignored", "Tell them 100% content transfer means the job is fully done, no explanation needed", "Content transfer completing is not the same as the entire job being finished — permissions and hyperlink steps run afterward and depend on content having landed first; ongoing activity is expected", "Tell them the activity is unrelated background maintenance, not part of their job"], correct: 2 },
  { body: "A client's IT team revoked and re-granted API access mid-migration. What should you check across the migration once access is restored?", options: ["Whether the entire migration needs to be re-scoped from zero", "Whether anything that was actively in-progress at the moment access was cut failed as a conflict — items mid-transfer when access drops may need manual review/retry rather than assuming clean resumption", "Whether the client's billing plan needs to be upgraded", "Whether only folders (not files) were affected, since files are unaffected by access loss"], correct: 1 },
  { body: "A client's report shows a much higher file count than they expected for their content volume. What's a reasonable first hypothesis before assuming a bug?", options: ["Assume the report is double-counting due to a system bug", "Confirm whether hidden/system files, versions, or nested duplicate structures are being counted — content systems often surface more granular items than a client's intuitive estimate", "Assume the client's original estimate must be corrected in writing before proceeding", "Assume duplicate migration jobs were accidentally started for the same account"], correct: 1 },
  { body: "A client asks why permission migration seems to be taking a very long time relative to how quickly their files moved. What do you check?", options: ["Check whether the client's internet connection slowed down specifically during this phase", "Check whether file transfer was actually incomplete despite showing 100%", "Permission migration involves comparing source and destination permission sets per item, inherently more work per item than a straight file copy — check whether the volume of collaborators/shared items is unusually high", "Check whether permissions are being migrated to the wrong destination account"], correct: 2 },
  { body: "In general terms, how do you think the system tracks \"what still needs to be done\" across potentially millions of files/folders, without checking every single item constantly?", options: ["A single global counter that increments as items complete, with no per-item detail", "Some form of status-tagged work queue/tracking table per item (not-started/in-progress/done/failed) that workers can poll and pick up in batches, rather than re-scanning everything from scratch repeatedly", "A live connection held open per file for the duration of the entire migration", "Re-scanning the entire source and destination from scratch before every status check"], correct: 1 },
  { body: "Why would a system that migrates both small and large files likely use two different internal processes for them, rather than one process handling all file sizes?", options: ["Small and large files are handled identically; the distinction is only cosmetic in reporting", "Large files are always migrated by a separate manual team, not automation", "Two processes exist only because of a licensing limit on file size per API call", "Different transfer methods suit different sizes (single-request vs. chunked/multi-part) — separating them lets each be tuned and scaled independently, so a slowdown in one doesn't necessarily bottleneck the other"], correct: 3 },
  { body: "How would you expect the system to know which items are eligible for automatic retry versus which need to surface for manual review, at a conceptual level?", options: ["All failures are retried the same fixed number of times regardless of cause", "It likely categorizes failures by type/reason and applies automatic retry only to categories understood to be commonly transient, flagging other failure types (e.g., permission/authorization issues) directly for review", "Manual review is triggered only after a client complaint is filed", "Retry eligibility is decided randomly to distribute system load evenly"], correct: 1 },
  { body: "Conceptually, how might the system avoid creating duplicate folders at the destination if a folder-creation step is retried after a partial failure?", options: ["It relies on the client to manually delete duplicates after migration", "It always deletes and recreates the folder from scratch on every retry", "It likely checks for an existing destination object matching the source item (by name/path or a persisted reference to what was already created) before attempting to create it again", "Duplicate folders are prevented only by cloud provider-side naming rules"], correct: 2 },
  { body: "How would you expect delta/incremental detection to differ architecturally for a platform that only exposes path-based changes vs. one that exposes ID-based change feeds?", options: ["Both platform types use an identical change-feed mechanism internally", "Path-based platforms simply disable delta migration entirely", "ID-based platforms require manual change confirmation from the client", "An ID-based platform likely allows direct polling of a change feed tied to stable identifiers; a path-based platform likely requires comparing current state against a previous snapshot to infer what changed"], correct: 3 },
  { body: "Why would hyperlink rewriting logically need to be a separate pass over already-migrated content, rather than something done inline during the initial file transfer?", options: ["Separate passes are required only for legal/compliance archiving reasons", "Hyperlinks are rewritten before transfer to save processing time later", "Rewriting a link correctly requires knowing the destination location of the link's target, which may not have migrated yet at the moment the file itself is being transferred — creating a natural ordering dependency", "This is a historical implementation choice with no functional dependency reason"], correct: 2 },
  { body: "At a conceptual level, why would a large-scale migration system generate a final report only after confirming several dependent sub-processes (content, permissions, hyperlinks) have each reached a resolved state, rather than on a fixed timer?", options: ["Fixed timers are avoided purely to reduce server load during reporting", "Reports are actually generated on a timer, but hidden from the client until requested", "This ordering only applies to migrations larger than a specific file count", "A fixed timer can't guarantee accuracy — report generation logically needs to wait for a genuine \"all dependent processes have reached a final state\" condition to avoid reporting a false completion"], correct: 3 },
  { body: "Why might a migration engine skip a file that already exists at the destination with matching size/timestamp during a re-run, rather than re-copying it?", options: ["It always re-copies every file on every run to guarantee data integrity", "Comparing existing items lets it avoid redundant transfer work and potential overwrite of legitimate content — treating a matching item as already migrated rather than blindly re-copying every time", "It skips files only when explicitly instructed by the client via a support ticket", "It skips the file permanently and never checks it again in any future run"], correct: 1 },
  { body: "Why would a system preserve original file timestamps (created/modified dates) during migration rather than stamping everything with the migration date?", options: ["Timestamps are always regenerated to reflect the migration date for audit purposes", "Preserving timestamps is only possible when migrating within the same cloud vendor", "Timestamps are irrelevant to migration and are never tracked either way", "Preserving original timestamps maintains an accurate historical record and version context for the client's content, which the migration date would overwrite and lose"], correct: 3 },
  { body: "Why might a client's migration report distinguish between \"skipped (already migrated)\" and \"failed\" rather than grouping both as incomplete?", options: ["The distinction exists only for internal engineering metrics, not client-facing meaning", "\"Skipped\" and \"failed\" are functionally identical and only differ by label", "Skipped items are always a subset of failed items that later self-resolved", "The two states mean very different things operationally — skipped items are already successfully present at destination and need no action, while failed items genuinely didn't transfer and need investigation; conflating them would obscure real problems"], correct: 3 },
]

async function main() {
  const testTitle = process.env.TEST_TITLE || 'Content Migration Assessment'
  const aptitudeBankName = process.env.APTITUDE_BANK_NAME || 'Freshers Assessment 1'
  const poolSize = Number(process.env.POOL_SIZE) || 20
  const durationMin = Number(process.env.DURATION_MIN) || 15

  // Only used to resolve the tenant/admin — this test's questions are entirely its own pool.
  const aptiBank = await prisma.questionBank.findFirst({ where: { name: aptitudeBankName } })
  if (!aptiBank) throw new Error(`Bank "${aptitudeBankName}" not found — needed to resolve tenant/admin.`)
  const tenantId = aptiBank.tenantId

  const admin = await prisma.user.findFirst({
    where: { tenantId, role: { in: ['SUPER_ADMIN', 'COMPANY_ADMIN'] } },
    orderBy: { createdAt: 'asc' },
  })
  if (!admin) throw new Error('No admin user found for the tenant.')

  let bank = await prisma.questionBank.findFirst({ where: { name: CONTENT_MIGRATION_BANK_NAME, tenantId } })
  if (!bank) {
    bank = await prisma.questionBank.create({ data: { name: CONTENT_MIGRATION_BANK_NAME, tenantId, description: 'Content migration engineering reasoning MCQ pool — workflow/sequence/dependency, troubleshooting triage, architecture reasoning.' } })
  }

  let created = 0
  for (let i = 0; i < CONTENT_MIGRATION_QUESTIONS.length; i++) {
    const title = `Content Migration Q${i + 1}`
    const existing = await prisma.question.findFirst({ where: { bankId: bank.id, title } })
    if (existing) continue
    const q = CONTENT_MIGRATION_QUESTIONS[i]
    await prisma.question.create({
      data: {
        bankId: bank.id, type: 'MCQ_SINGLE', title, body: q.body,
        difficulty: 'MEDIUM', points: 1, domain: 'Content Migration Engineering',
        options: { create: q.options.map((text, idx) => ({ text, isCorrect: idx === q.correct, order: idx })) },
      },
    })
    created++
  }
  console.log(`Content Migration bank: ${created} question(s) created, ${CONTENT_MIGRATION_QUESTIONS.length - created} already existed.`)

  const questions = await prisma.question.findMany({
    where: { bankId: bank.id, title: { startsWith: 'Content Migration Q' } },
    orderBy: { createdAt: 'asc' },
    select: { id: true },
  })
  if (questions.length < poolSize) throw new Error(`Only ${questions.length} migration questions — need at least ${poolSize}.`)

  const instructions = `Content Migration Assessment — ${durationMin} minutes, a random ${poolSize} of ${questions.length} questions, 1 mark each. Choose the best option.`

  let test = await prisma.test.findFirst({ where: { title: testTitle, tenantId } })
  if (!test) {
    test = await prisma.test.create({
      data: {
        title: testTitle, domain: 'Content Migration Engineering', duration: durationMin,
        status: TestStatus.DRAFT, proctoring: true, enforceViolations: false, sebRequired: false,
        tenantId, createdById: admin.id, instructions,
      },
    })
    console.log(`created test "${testTitle}"`)
  } else {
    const secs = await prisma.testSection.findMany({ where: { testId: test.id } })
    for (const s of secs) await prisma.testQuestion.deleteMany({ where: { sectionId: s.id } })
    await prisma.testSection.deleteMany({ where: { testId: test.id } })
    await prisma.test.update({ where: { id: test.id }, data: { duration: durationMin, instructions } })
    console.log(`rebuilt existing test "${testTitle}"`)
  }

  const section = await prisma.testSection.create({
    data: { testId: test.id, title: 'Content Migration Engineering', skill: 'GENERAL', order: 0, timeLimit: durationMin * 60, pickCount: poolSize,
      description: `${poolSize} questions (randomly drawn from a bank of ${questions.length}) covering content migration workflow, troubleshooting, and architecture reasoning. 1 mark each.` },
  })
  await prisma.testQuestion.createMany({
    data: questions.map((q, i) => ({ testId: test!.id, sectionId: section.id, questionId: q.id, order: i, points: 1 })),
  })

  console.log(`\n✅ "${testTitle}": ${poolSize}/${questions.length} questions, ${durationMin} min, ${poolSize} marks. Status DRAFT — publish it in the admin UI to use.`)
}

if (require.main === module) {
  main().catch(e => { console.error('❌ create-content-migration-assessment failed:', e); process.exit(1) }).finally(() => prisma.$disconnect())
}
