/**
 * Create/rebuild "Email Migration Assessment":
 *   20 questions in 15 minutes, 20 marks — randomly drawn from a 50-question
 *   mailbox migration engineering pool (folder/one-time-delta reasoning,
 *   troubleshooting triage, architecture reasoning), one section, MCQ,
 *   1 mark each.
 *
 * NOTE (per the source material's own caveat): unlike Content/Message
 * Migration, this pool is not grounded in documented internal CloudFuze Email
 * workflow logic — it's a first draft built from the visible report structure
 * (Job -> Pair -> Folder, One-Time/Delta tabs, per-folder status) plus
 * transferable reasoning from Content/Message migration behavior. Flag
 * anything that doesn't match real CloudFuze Email behavior for correction.
 *
 * The source material was written as open-ended reasoning questions with a
 * rubric for AI/human grading, not as MCQs. Per explicit instruction
 * (mirroring Content/Message Migration Assessment), each was converted into a
 * 4-option MCQ: the correct option is the original reasoning, condensed; the
 * 3 distractors are plausible-but-wrong statements written to test the same
 * concept.
 *
 * Idempotent — safe to re-run: questions are only created if missing (matched
 * by title), and the test's section is cleanly rebuilt each run so pool
 * size/timing always match this script, without touching the question bank.
 *
 *   docker exec -w /app neutaraassessment-backend-1 npx tsx prisma/create-email-migration-assessment.ts
 *
 * Env overrides: TEST_TITLE (default "Email Migration Assessment"),
 *                APTITUDE_BANK_NAME (default "Freshers Assessment 1" — used only
 *                to resolve the tenant/admin, not as a question source),
 *                POOL_SIZE (default 20), DURATION_MIN (default 15).
 */
import { PrismaClient, TestStatus } from '@prisma/client'
const prisma = new PrismaClient()

export const EMAIL_MIGRATION_BANK_NAME = 'Email Migration Questions Bank'

export const EMAIL_MIGRATION_QUESTIONS: { body: string; options: string[]; correct: number }[] = [
  { body: "Why would a mailbox migration process folders (Inbox, Sent, Drafts, etc.) largely independently of each other rather than requiring them to finish in a fixed order?", options: ["Folders must always complete in alphabetical order to satisfy platform requirements", "Independent processing only happens because Trash and Spam are excluded by default", "Folders are generally self-contained collections of messages without a structural dependency on each other — parallel, independent progress across folders is expected, not evidence of anything wrong", "Folders depend on each other in the same way parent/child folders do in content migration"], correct: 2 },
  { body: "A pair shows Inbox, Sent, and Drafts as \"Processed\" while Trash is still \"In Queue,\" with the overall pair only partway complete. Is this a problem?", options: ["Yes — all folders must always complete in the same order they appear in the mailbox", "Yes — Trash lagging always indicates a corrupted mailbox migration", "Not inherently — it likely reflects folder size/volume differences and queue ordering, not a dependency failure; since folders don't block each other, one lagging while others finish is normal", "Not a problem, but only because Trash is always migrated last by fixed design"], correct: 2 },
  { body: "Why would an email migration need both a \"one-time\" and a \"delta\" mode, the same way content migration does?", options: ["One-time only migrates folders; delta only migrates individual messages", "Delta exists purely to reduce the client's invoice, with no functional difference otherwise", "One-time and delta are the same process; the labels differ only for reporting purposes", "The one-time pass captures everything as of when it runs; email keeps arriving throughout a transition period, so delta exists to keep catching new/changed mail after the initial pass, right up until final cutover"], correct: 3 },
  { body: "Why might a client need delta sync to keep running for weeks after the one-time migration shows complete, rather than just running one-time again later?", options: ["One-time cannot technically be re-run more than once per mailbox", "Delta only exists to satisfy a compliance requirement, unrelated to efficiency", "Running one-time again would actually be faster, but delta is used for auditing purposes only", "Re-running one-time again would mean re-processing everything from scratch, which is wasteful and slow; delta is specifically designed to catch only what's changed since the last pass"], correct: 3 },
  { body: "Why would email migration typically require some form of admin-level consent/authorization on both source and destination, rather than each individual user's own login?", options: ["Individual user logins are actually required in addition to admin consent for every mailbox", "Admin consent is only needed for calendar and contacts, not for mail itself", "Admin-level consent exists purely as a billing checkpoint, not an access mechanism", "Migrating many users' mailboxes at scale isn't practical one login at a time — an admin-level grant typically allows the migration tool to act across the whole organization's mailboxes"], correct: 3 },
  { body: "What happens, logically, if admin consent/API access is revoked partway through a migration?", options: ["The entire migration job is permanently deleted the moment access is revoked", "Already-processed items are automatically rolled back and re-queued from scratch", "Revoking access has no effect on an in-progress migration since it was already authorized once", "Anything actively relying on that access at that moment would be expected to fail or stall — items already fully processed should remain intact, but new work can't proceed until access is restored"], correct: 3 },
  { body: "Why would calendar and contacts sometimes migrate on a noticeably different timeline than the mailbox's actual email content, even for the same user?", options: ["Calendar and contacts are always migrated only after 100% of email content completes", "A timeline difference always indicates the calendar or contacts data is corrupted", "Calendar, contacts, and email are always processed through the exact same API calls, so no timeline difference should ever occur", "These are often distinct data types/APIs within the same account rather than a single unified data stream — treating them as separate workstreams that can progress at their own pace is expected"], correct: 3 },
  { body: "Why does a shared mailbox or delegated-access mailbox need different handling than a standard individual mailbox, even if all the mail itself migrates successfully?", options: ["Shared mailboxes require no different handling; delegation is preserved automatically with the mail", "Shared mailboxes are technically identical to individual mailboxes on every platform", "Delegated access is a UI-only setting that has no bearing on actual migration behavior", "The mail content migrating doesn't automatically preserve who else has legitimate access to that mailbox — delegation/shared-access permissions are a separate thing that needs to be identified and replicated"], correct: 3 },
  { body: "Why would folder mapping (e.g., source \"Archive\" to destination equivalent) sometimes require explicit configuration rather than always mapping automatically 1:1?", options: ["Folder mapping is always automatic and 1:1 regardless of platform differences", "Explicit mapping is only needed for Trash and Spam, never for other folders", "Folder mapping configuration exists purely as an optional cosmetic renaming feature", "Source and destination platforms don't always have identically-named or identically-structured default folders — explicit mapping avoids silently misplacing mail into the wrong destination equivalent"], correct: 3 },
  { body: "Why might \"Processed\" for a folder not fully guarantee every single message inside actually landed correctly, in the same way folder-level and file-level status can diverge in content migration?", options: ["\"Processed\" is a mathematically exact guarantee with zero possibility of individual message issues", "Folder-level status only reflects the very first message in the folder, not the rest", "Message-level failures always automatically revert the entire folder to \"In Queue\"", "Folder-level status is typically a rollup of many individual message-level outcomes — a small number of individual message failures within an otherwise-successful folder could still exist and need their own status check"], correct: 3 },
  { body: "Why would very large mailboxes (heavy attachment volume) take proportionally longer than mailbox count alone would suggest?", options: ["Attachments are always migrated separately after all mail content is fully complete", "Attachment volume only affects calendar migration, not email folders", "Time-per-mailbox depends only on message count, never on attachment size", "Message count isn't the same as data volume — attachments add substantial transfer weight per message that a simple message-count comparison across mailboxes wouldn't capture"], correct: 3 },
  { body: "Why does email migration typically need to preserve original send/received timestamps rather than showing the migration's actual transfer time?", options: ["Timestamps are always regenerated to reflect migration time for audit logging purposes", "Timestamp preservation is optional and has no bearing on user search/sort behavior", "Original timestamps are only preserved for Sent items, never for Inbox", "Email is fundamentally a chronological record for the user (sorting, searching, compliance/legal reference) — losing the true original timestamp would functionally break how the user relies on their mail history"], correct: 3 },
  { body: "Why would a client ask whether email migration preserves read/unread status, and why does that matter operationally?", options: ["Read/unread status has no operational impact and is purely cosmetic metadata", "Read/unread status is always lost during migration on every platform, with no exceptions", "This only matters for shared mailboxes, never for individual mailboxes", "It affects the user's actual experience post-migration — if previously-read mail shows as unread, it creates confusion and potentially makes users think mail is \"new\" when it isn't"], correct: 3 },
  { body: "Why might migrating \"Sent\" and \"Drafts\" require different handling considerations than \"Inbox,\" even though structurally they're just more folders?", options: ["Sent and Drafts are never actually migrated, only Inbox and Trash are supported", "Sent and Drafts always use a completely separate migration engine unrelated to Inbox", "There is no meaningful difference; these folders are always processed identically in every respect", "Sent/Drafts can involve specific metadata nuances (draft state, sender-vs-recipient framing) that differ subtly from a straightforward received message"], correct: 3 },
  { body: "Why would spam/junk and trash folders sometimes be treated as lower priority or optional in some migration configurations?", options: ["Spam and trash are technically impossible to migrate on any platform", "These folders are always migrated first, ahead of Inbox, to clear them out of the way", "Deprioritizing these folders is always a system-enforced default with no client choice involved", "These often contain content the user doesn't actually need preserved long-term — some clients may deliberately deprioritize or exclude them to reduce total migration volume/time"], correct: 3 },
  { body: "Why would a client's total mailbox count estimate not match the actual total count the migration reports?", options: ["The migration tool always over-counts by a fixed percentage regardless of mailbox content", "A mismatch always means duplicate migration jobs were started for the same mailbox", "Client estimates are always accurate, so any mismatch must be a reporting bug", "Mail systems can include items a client didn't mentally count (e.g., RSS feed folders, snoozed items, hidden system folders) — worth checking what's actually being counted before assuming a discrepancy is an error"], correct: 3 },
  { body: "Why would an email migration pair need to track \"Total Count\" versus \"Processed Count\" at the pair level, in addition to folder-level status?", options: ["Pair-level counts exist only for billing reconciliation, not progress tracking", "Folder-level status alone is always sufficient; pair-level counts are redundant and unused", "Total Count and Processed Count are always identical values shown for consistency only", "Gives a quick overall progress signal without needing to open every folder individually — useful for both the client's dashboard view and the engineer's own quick health-check of a given pair"], correct: 3 },
  { body: "Why might one pair in a batch of many user mailboxes progress much faster than another, even if both users have similar-looking mailbox sizes?", options: ["Processing speed is always identical for mailboxes of the same total size", "Speed differences only occur due to which day of the week the migration started", "One mailbox always processes faster purely based on alphabetical username order", "Actual content composition can differ significantly even at similar total sizes — attachment-heavy mail, folder structure complexity, or per-item processing overhead can vary meaningfully between users"], correct: 3 },
  { body: "Why would a client ask about migrating \"In-Place Archive\" or older archived mail separately from their primary mailbox?", options: ["In-Place Archive is always automatically merged into Inbox before migration begins", "Archived mail is never migratable under any circumstances and must be manually exported", "Archive folders are always included by default with zero configuration needed, on every platform", "Archived mail is sometimes stored in a structurally distinct location/system from the active mailbox even for the same user — it may need its own discovery/migration path"], correct: 3 },
  { body: "Why does a mailbox migration typically need rate-limit-aware throttling, similar in spirit to content/message migration?", options: ["Throttling exists only to intentionally slow down migrations for larger clients", "Rate limits only apply to calendar data, never to email messages themselves", "Mail platforms never impose any API limits, so throttling is purely precautionary and unnecessary", "Mail platforms' APIs impose their own request/quota limits — migrating at scale without respecting those limits risks getting throttled or temporarily blocked"], correct: 3 },
  { body: "Why would a migration tool verify final counts match between source and destination after \"completion,\" rather than trusting the process completed correctly by default?", options: ["Count verification is purely a formality required for the client invoice, not a real check", "A process that reports no errors is always guaranteed to be fully accurate with no need for verification", "Verification only checks folder names, not actual message counts", "Verification catches silent gaps (an item that appeared to succeed but didn't actually land, or was missed by the discovery step) that wouldn't otherwise surface"], correct: 3 },
  { body: "Why might a client's calendar invites/meeting data require special handling around time zones during migration?", options: ["Time zones only matter for recurring meetings, never for one-time events", "Calendar data is always stored in a single universal time zone with no conversion needed", "Time zone handling is a client-side display setting unrelated to the migration process itself", "Calendar data is time-zone sensitive by nature — a naive migration that doesn't correctly account for time zone context could shift meeting times incorrectly for the user"], correct: 3 },
  { body: "Why would a client ask whether migrated email retains its original folder structure exactly, versus being reorganized during migration?", options: ["Folder structure is always flattened into a single folder by default on every migration", "Folder structure preservation has no bearing on user experience since search always works regardless", "Original folder structure is technically impossible to preserve across any two platforms", "Users build muscle memory and workflows around their folder structure — preserving it (unless explicitly asked to restructure) avoids breaking the user's actual working habits"], correct: 3 },
  { body: "Why does a \"Switch to New Reports\" type toggle existing on a reporting dashboard suggest something worth confirming with your team before assuming all clients see the same thing?", options: ["The toggle only affects color theme, never the actual data or structure shown", "All clients are always automatically migrated to the new report view simultaneously", "The old report view is disabled the instant the new one launches, so both can never coexist", "If both an old and new reporting view exist in parallel, different clients or different in-progress jobs might be rendering in different UI versions — worth confirming which one a given client is actually looking at"], correct: 3 },
  { body: "Why would a client's mailbox pair show \"In Progress\" at the top level even though every individual folder shown underneath already says \"Processed\"?", options: ["This combination is technically impossible and always indicates a display bug", "Top-level status always lags folder-level status by exactly one full day regardless of cause", "\"In Progress\" at the top level while folders show \"Processed\" always means the report is cached and stale", "There may be folders not currently visible/expanded in the view, or a final reconciliation/verification step pending after individual folders complete"], correct: 3 },
  { body: "A client's pair shows 8,197 of 65,864 total processed, with several folders already fully \"Processed.\" Is this concerning, and what would you check?", options: ["Always concerning — any pair below 50% processed should be escalated immediately", "Assume the count is wrong and manually recalculate the percentage before doing anything else", "Assume the smaller folders are secretly failing since the total percentage looks low", "Not inherently concerning on its own — check whether the still-pending folders (e.g., a large Inbox or Trash) account for the bulk of the remaining count; only escalate if progress has genuinely stopped moving"], correct: 3 },
  { body: "A client asks why their migration shows \"In Progress\" with no visible errors, but hasn't moved in several hours. First check?", options: ["Immediately restart the entire mailbox migration from the very beginning", "Assume the client's mailbox is too large to ever complete and recommend splitting it", "Check only the client's internet connection, since that's always the root cause", "Confirm whether this is a true stall (zero movement over a meaningful window) versus simply a large remaining folder processing slowly — then check for any authentication/access issues"], correct: 3 },
  { body: "A client's calendar events show up shifted by several hours after migration. What do you check first?", options: ["Check only whether the client's computer clock is set correctly", "Assume the events were manually edited by the client after migration", "Assume this is unrelated to migration and is a display-only issue in the client's calendar app", "Check time zone handling specifically — this is a known class of issue for calendar data and should be verified directly rather than assumed to be a general migration error"], correct: 3 },
  { body: "A shared/delegated mailbox migrated all its mail successfully, but a second person who used to have access can no longer access it at the destination. What's your triage?", options: ["Assume the mail migration itself failed silently for that specific user", "Assume the second person's account was deleted at the destination platform", "Re-migrate the entire shared mailbox from scratch to fix the access issue", "Recognize this as a permissions/delegation gap distinct from mail-content migration — check whether delegation/shared-access setup was configured at the destination at all"], correct: 3 },
  { body: "A client insists they had far fewer emails than the migration is reporting. What do you check?", options: ["Assume the migration tool duplicated every message during transfer", "Assume the client's original estimate must be corrected in writing before proceeding", "Assume a second mailbox was accidentally merged into this migration job", "Check whether hidden/system folders (RSS feeds, snoozed items, junk, etc.) are being included in the total count that the client didn't mentally account for"], correct: 3 },
  { body: "A client's admin revoked and re-granted access mid-migration due to an internal security review. What should you check once access is restored?", options: ["Assume the entire migration must be re-scoped and restarted from zero", "Assume only calendar data was affected, since email uses a separate access grant", "Assume access revocation has no impact once it's re-granted, regardless of timing", "Check what was actively being processed at the exact moment access was cut — those specific items may need review/retry rather than assuming everything resumed cleanly"], correct: 3 },
  { body: "One user's mailbox pair is taking dramatically longer than every other similarly-sized mailbox in the same batch. What's a reasonable first hypothesis?", options: ["Assume the entire batch migration process is fundamentally broken", "Assume this user's account was incorrectly included in the batch and should be removed", "Assume alphabetical processing order is simply disadvantaging this particular user", "Consider actual content composition differences (attachment-heavy mail, unusually large individual folders, or a specific problematic item causing repeated delays) rather than assuming the whole batch is broken"], correct: 3 },
  { body: "A client asks why delta sync appears to have \"missed\" some emails sent right before a scheduled sync run. What do you check?", options: ["Assume delta sync is fundamentally broken and switch to one-time migration permanently", "Assume the emails were sent to a folder that delta never checks", "Assume the client's email client cached an outdated view and ignore the report", "Check the actual timing of when delta last ran/checked relative to when those specific emails arrived — a genuinely narrow timing gap is a very different situation than delta being broken outright"], correct: 3 },
  { body: "A client reports their read/unread status doesn't match after migration. What do you check, and how do you frame this to the client?", options: ["Tell the client this is always fully guaranteed and must be a bug in their case specifically", "Tell the client read/unread status is never trackable on any platform, so nothing can be done", "Assume the client misremembers which emails they had read before migration", "Confirm whether read/unread state preservation is expected/supported behavior for this specific migration configuration at all — frame it based on what's actually expected"], correct: 3 },
  { body: "A client's folder structure appears reorganized/flattened at the destination compared to source. What's your first question?", options: ["Assume the destination platform is incapable of supporting nested folders at all", "Assume this always indicates a corrupted migration requiring a full restart", "Assume the client accidentally reorganized their own folders after migration", "Confirm whether folder mapping was configured to preserve structure exactly, or whether some folders don't have a direct destination equivalent and were mapped differently"], correct: 3 },
  { body: "A client viewing an older bookmarked report link says it looks different from what your team sees internally. What do you check?", options: ["Assume the client's browser is outdated and needs to be updated", "Assume the client's report link has expired and issue a completely new migration job", "Assume the underlying migration data itself differs between what the client and team see", "Check whether they're viewing an old vs. new reporting UI version — if both exist in parallel, this kind of mismatch is a legitimate, explainable cause"], correct: 3 },
  { body: "A client's pair shows all folders \"Processed\" individually, but the overall pair status still says \"In Progress.\" What do you check?", options: ["Assume the pair-level status is simply a display bug and tell the client to ignore it", "Assume the migration must be restarted since the two statuses conflict", "Assume the client is viewing a cached page and instruct them to clear their browser cache", "Look for any folders not visible in the current view, or a final verification/reconciliation step that may run after individual folder completion"], correct: 3 },
  { body: "Conceptually, how would you expect the system to track progress across many folders per mailbox without needing to fully reprocess previously completed folders?", options: ["It re-scans every folder from scratch on every status check, regardless of prior progress", "It only tracks status at the mailbox level, with no per-folder granularity at all", "It relies on the client to manually mark which folders have already completed", "It likely tracks status per folder/item (not yet started / in progress / done / failed) similar to content and message migration's item-level status tracking"], correct: 3 },
  { body: "Why would delta detection for email likely rely on some form of \"last checked\" timestamp or change marker, similar in spirit to content's delta approach?", options: ["Delta detection for email doesn't require any reference point since mail servers push changes automatically", "A \"last checked\" marker is used only for compliance logging, not for determining what to scan", "Delta always re-scans the entire mailbox regardless of any previous checkpoint, by design", "Without a reference point for \"what was already captured,\" every delta run would need to re-scan everything to find what's new — a persisted marker lets each run efficiently look only at what's changed"], correct: 3 },
  { body: "How would you expect the system to handle a mailbox with an enormous number of very small messages differently than a mailbox with far fewer but much larger (attachment-heavy) messages, at a processing level?", options: ["Both mailbox types are processed with an identical fixed batch size regardless of content", "Attachment-heavy mailboxes are always processed message-by-message with no batching at all", "High message-count mailboxes are always slower than attachment-heavy ones of the same total size", "It likely batches/paginates high message-count mailboxes to process many items efficiently per request, while attachment-heavy mailboxes are more constrained by data volume/transfer time per item"], correct: 3 },
  { body: "Conceptually, why would folder-to-folder mapping logic need to be resolved before actual message transfer begins for a given folder, rather than resolved on the fly per message?", options: ["Per-message mapping is actually more efficient and is the standard approach", "Folder mapping is resolved only after all messages have already been transferred", "Mapping resolution timing has no bearing on consistency or efficiency either way", "Every message in a folder shares the same destination target — resolving the mapping once per folder rather than per message avoids redundant lookups and ensures consistency"], correct: 3 },
  { body: "How might the system be expected to reconcile source and destination counts to verify true completion, at a conceptual level?", options: ["It declares completion purely based on the absence of any reported errors, with no count comparison", "It relies entirely on the client to manually verify counts before considering the job done", "It compares counts only for Inbox, since other folders don't require reconciliation", "It likely compares a final count/checksum of items successfully written at destination against the discovered count from source, flagging any shortfall for investigation"], correct: 3 },
  { body: "Why would admin-level consent/authorization architecture make sense for a tool migrating many users' mailboxes at organizational scale, versus requiring individual user logins?", options: ["Individual logins would actually be faster to set up than a single admin-level grant", "Admin-level consent is required only for calendar data, not for the mailboxes themselves", "This architecture exists solely to simplify billing, not to enable access at scale", "Organizational-scale migration needs to act across potentially thousands of mailboxes without requiring each individual user to separately authenticate — an admin-granted, tenant-wide permission model is the only practical way to operate at that scale"], correct: 3 },
  { body: "Why might a client ask whether their inbox rules/filters (e.g., auto-sort into folders) carry over during migration?", options: ["Rules and filters are always embedded inside each message, so they migrate automatically with the mail", "Rules and filters are universally unsupported across all mail platforms and can never be migrated", "Rules only need to be recreated if the client's mailbox is a shared mailbox", "Rules/filters are typically a separate configuration layer from the mail content itself — migrating the messages doesn't automatically recreate the rules that would apply to future incoming mail"], correct: 3 },
  { body: "Why might individual message or attachment size limits on the destination platform require special handling during migration?", options: ["Size limits are identical across every mail platform, so this never actually comes up in practice", "Oversized messages are automatically compressed losslessly by the migration engine with no client involvement", "Size limits only apply to calendar invites, never to regular email messages", "If a source message or attachment exceeds a size limit enforced by the destination, it can't be posted as-is — this needs a defined handling behavior rather than being silently dropped or assumed to always fit"], correct: 3 },
  { body: "Why would out-of-office/auto-reply settings need explicit consideration during a mailbox migration, rather than assuming they'll just carry over with the mailbox?", options: ["Auto-reply settings are always disabled automatically during any migration, by design", "Auto-reply settings are part of every individual email message and migrate with each one", "This setting is irrelevant since it only affects incoming mail after migration is fully complete", "Auto-reply configuration is a mailbox setting distinct from message content — if it isn't explicitly migrated or reconfigured, a user could unexpectedly lose their active auto-reply at the destination"], correct: 3 },
  { body: "Why might a client ask about migrating a distribution list or group mailbox differently than an individual user's mailbox?", options: ["Distribution lists are functionally identical to individual mailboxes with no additional considerations needed", "Group mailboxes cannot be migrated under any circumstances and must be manually recreated", "Membership always transfers automatically the instant any mail from the group migrates", "A distribution list/group mailbox often has its own membership and access model — its mail migrating doesn't guarantee its membership list or send-as permissions were also replicated, similar to the shared-mailbox delegation concern"], correct: 3 },
  { body: "Why would encrypted or rights-protected email (e.g., items under legal hold or DRM-style protection) potentially require different handling than standard mail during migration?", options: ["Encrypted mail always migrates identically to unencrypted mail with zero additional considerations", "Encryption is automatically stripped from all messages the moment migration begins", "Only calendar data can ever be encrypted, so this consideration never applies to email itself", "Protected content may not be readable/transferable through the standard migration path without the appropriate decryption context or permission — this is a category worth identifying explicitly"], correct: 3 },
  { body: "Why might a client ask about a PST/export-file-based ingestion path for email, similar to the JSON-export concept in message migration?", options: ["Export-file-based migration is always faster and is therefore the default recommended path", "This approach only applies to mailboxes larger than a fixed size threshold", "PST/export-based ingestion is purely a legacy option with no real use case today", "Some environments may not expose full live API access (compliance-locked tenants, decommissioned/offline mailboxes, or client IT policy) — an export-file-based ingestion path lets migration proceed from a client-provided data file instead"], correct: 3 },
  { body: "Why does email signature/formatting fidelity (fonts, embedded images, HTML layout) matter as a migration consideration, not just the raw text content of a message?", options: ["Formatting is stripped from all emails as a standard, expected part of every migration", "Signature/formatting fidelity only matters for Sent items, never for received mail", "HTML formatting has no bearing on user experience since only plain text is ever displayed by mail clients", "A message that migrates with its plain text intact but loses formatting/embedded images may look broken or unprofessional to the user even though the \"content\" technically transferred"], correct: 3 },
]

async function main() {
  const testTitle = process.env.TEST_TITLE || 'Email Migration Assessment'
  const aptitudeBankName = process.env.APTITUDE_BANK_NAME || 'Freshers Assessment 1'
  const poolSize = Number(process.env.POOL_SIZE) || 20
  const durationMin = Number(process.env.DURATION_MIN) || 15

  // Only used to resolve the tenant/admin — this test's questions are entirely its own pool.
  const aptiBank = await prisma.questionBank.findFirst({ where: { name: aptitudeBankName } })
  if (!aptiBank) throw new Error(`Bank "${aptitudeBankName}" not found — needed to resolve tenant/admin.`)
  const tenantId = aptiBank.tenantId

  const admin = await prisma.user.findFirst({
    where: { tenantId, role: { in: ['SUPER_ADMIN', 'COMPANY_ADMIN'] } },
    orderBy: { createdAt: 'asc' },
  })
  if (!admin) throw new Error('No admin user found for the tenant.')

  let bank = await prisma.questionBank.findFirst({ where: { name: EMAIL_MIGRATION_BANK_NAME, tenantId } })
  if (!bank) {
    bank = await prisma.questionBank.create({ data: { name: EMAIL_MIGRATION_BANK_NAME, tenantId, description: 'Email/mailbox migration engineering reasoning MCQ pool — folder/one-time-delta reasoning, troubleshooting triage, architecture reasoning. First-draft pool (not yet validated against documented CloudFuze Email workflow).' } })
  }

  let created = 0
  for (let i = 0; i < EMAIL_MIGRATION_QUESTIONS.length; i++) {
    const title = `Email Migration Q${i + 1}`
    const existing = await prisma.question.findFirst({ where: { bankId: bank.id, title } })
    if (existing) continue
    const q = EMAIL_MIGRATION_QUESTIONS[i]
    await prisma.question.create({
      data: {
        bankId: bank.id, type: 'MCQ_SINGLE', title, body: q.body,
        difficulty: 'MEDIUM', points: 1, domain: 'Email Migration Engineering',
        options: { create: q.options.map((text, idx) => ({ text, isCorrect: idx === q.correct, order: idx })) },
      },
    })
    created++
  }
  console.log(`Email Migration bank: ${created} question(s) created, ${EMAIL_MIGRATION_QUESTIONS.length - created} already existed.`)

  const questions = await prisma.question.findMany({
    where: { bankId: bank.id, title: { startsWith: 'Email Migration Q' } },
    orderBy: { createdAt: 'asc' },
    select: { id: true },
  })
  if (questions.length < poolSize) throw new Error(`Only ${questions.length} email migration questions — need at least ${poolSize}.`)

  const instructions = `Email Migration Assessment — ${durationMin} minutes, a random ${poolSize} of ${questions.length} questions, 1 mark each. Choose the best option.`

  let test = await prisma.test.findFirst({ where: { title: testTitle, tenantId } })
  if (!test) {
    test = await prisma.test.create({
      data: {
        title: testTitle, domain: 'Email Migration Engineering', duration: durationMin,
        status: TestStatus.DRAFT, proctoring: true, enforceViolations: false, sebRequired: false,
        tenantId, createdById: admin.id, instructions,
      },
    })
    console.log(`created test "${testTitle}"`)
  } else {
    const secs = await prisma.testSection.findMany({ where: { testId: test.id } })
    for (const s of secs) await prisma.testQuestion.deleteMany({ where: { sectionId: s.id } })
    await prisma.testSection.deleteMany({ where: { testId: test.id } })
    await prisma.test.update({ where: { id: test.id }, data: { duration: durationMin, instructions } })
    console.log(`rebuilt existing test "${testTitle}"`)
  }

  const section = await prisma.testSection.create({
    data: { testId: test.id, title: 'Email Migration Engineering', skill: 'GENERAL', order: 0, timeLimit: durationMin * 60, pickCount: poolSize,
      description: `${poolSize} questions (randomly drawn from a bank of ${questions.length}) covering email migration workflow, troubleshooting, and architecture reasoning. 1 mark each.` },
  })
  await prisma.testQuestion.createMany({
    data: questions.map((q, i) => ({ testId: test!.id, sectionId: section.id, questionId: q.id, order: i, points: 1 })),
  })

  console.log(`\n✅ "${testTitle}": ${poolSize}/${questions.length} questions, ${durationMin} min, ${poolSize} marks. Status DRAFT — publish it in the admin UI to use.`)
}

if (require.main === module) {
  main().catch(e => { console.error('❌ create-email-migration-assessment failed:', e); process.exit(1) }).finally(() => prisma.$disconnect())
}
