-- Add FACE_OBSTRUCTED and SUSPECTED_ASSISTANCE to ProctoringEventType enum
ALTER TYPE "ProctoringEventType" ADD VALUE IF NOT EXISTS 'FACE_OBSTRUCTED';
ALTER TYPE "ProctoringEventType" ADD VALUE IF NOT EXISTS 'SUSPECTED_ASSISTANCE';
